{{ $serviceAccountName := include "base.serviceAccountName" $ }}
{{ $serviceAccountNamespace := include "base.serviceAccountNamespace" $ }}
{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccountName }}
  namespace: {{ $serviceAccountNamespace }}
  labels:
    {{- include "base.labels" $ | nindent 4 }}
{{ end }}
